### PR TITLE
Add syntax highlighting to multiline code blocks

### PR DESCRIPTION
**Pull request by jfranciscosousa**
Uses primsjs under the hood

### CODE REVIEW

**Comment by rafaelferreira6** [comment]
I think I prefer a darker editor. Since we are using `Prismjs`, can we use _Tomorrow night_ or similar? TIA

**Review by rafaelferreira6 — CHANGES_REQUESTED** [review]
Can we use PT Mono instead of Monaco please? To ensure consistency with the rest.

**Comment by jfranciscosousa** [comment]
@rafaelferreira6 it will have PT Mono once it's merged with master. I didn't add that on this PR

**Review by rafaelferreira6 — APPROVED** [review]
Since PT Mono will replace Monaco after merging into the master, everything else LGTM

**Pull request merged**
